/**
 * cashfreeService — loads the Cashfree SDK and requests a backend-generated payment session id.
 */

import { CASHFREE_APP_ID, CASHFREE_ENV } from '../config/env.js';

const CASHFREE_PAYMENT_SESSION_ENDPOINT = '/api/cashfree/session';
const CASHFREE_VERIFY_ENDPOINT = '/api/cashfree/verify';
const CASHFREE_SCRIPT_URL = 'https://sdk.cashfree.com/js/v3/cashfree.js';
const PENDING_REGISTRATION_KEY = 'plynity_pending_registration';

let cashfreeScriptLoadingPromise = null;

function parseApiError(response, text) {
  if (!text) {
    return `Payment server error (${response.status}).`;
  }

  try {
    const data = JSON.parse(text);
    return (
      data?.error?.message ||
      (typeof data?.error === 'string' ? data.error : null) ||
      data?.message ||
      data?.error ||
      text
    );
  } catch {
    return text;
  }
}

export function buildCashfreeReturnUrl() {
  const url = new URL(window.location.href);
  url.searchParams.delete('order_id');
  url.searchParams.delete('payment_return');
  url.searchParams.set('payment_return', '1');
  url.searchParams.set('order_id', '{order_id}');
  return url.toString();
}

export function savePendingRegistration(payload) {
  sessionStorage.setItem(PENDING_REGISTRATION_KEY, JSON.stringify(payload));
}

export function loadPendingRegistration() {
  const raw = sessionStorage.getItem(PENDING_REGISTRATION_KEY);
  if (!raw) return null;

  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export function clearPendingRegistration() {
  sessionStorage.removeItem(PENDING_REGISTRATION_KEY);
}

export function loadCashfreeScript() {
  if (typeof window === 'undefined') {
    return Promise.resolve(false);
  }

  if (window.Cashfree) {
    console.log('[Cashfree] SDK already available on window.');
    return Promise.resolve(true);
  }

  if (cashfreeScriptLoadingPromise) {
    return cashfreeScriptLoadingPromise;
  }

  const existingScript = document.querySelector(`script[src="${CASHFREE_SCRIPT_URL}"]`);

  cashfreeScriptLoadingPromise = new Promise((resolve) => {
    const onLoaded = () => {
      if (window.Cashfree) {
        console.log('[Cashfree] SDK loaded successfully.');
        resolve(true);
      } else {
        console.error('[Cashfree] Script loaded but window.Cashfree is not available.');
        resolve(false);
      }
    };

    const onError = (event) => {
      console.error('[Cashfree] Failed to load SDK script.', event);
      resolve(false);
    };

    if (existingScript) {
      existingScript.addEventListener('load', onLoaded, { once: true });
      existingScript.addEventListener('error', onError, { once: true });
      return;
    }

    const script = document.createElement('script');
    script.src = CASHFREE_SCRIPT_URL;
    script.async = true;
    script.onload = onLoaded;
    script.onerror = onError;
    document.body.appendChild(script);
  });

  return cashfreeScriptLoadingPromise;
}

export async function createCashfreePaymentSession({
  orderId,
  amount,
  customerName,
  customerEmail,
  customerPhone,
  orderNote,
  returnUrl,
}) {
  if (!CASHFREE_APP_ID) {
    throw new Error('Cashfree app ID is not configured. Please set VITE_CASHFREE_APP_ID.');
  }

  if (!orderId || !amount) {
    throw new Error('Order ID or amount missing while creating Cashfree payment session.');
  }

  console.log('[Cashfree] Creating payment session with backend...', {
    orderId,
    amount,
    customerEmail,
    mode: CASHFREE_ENV,
    returnUrl,
  });

  let response;
  try {
    response = await fetch(CASHFREE_PAYMENT_SESSION_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        orderId,
        amount,
        currency: 'INR',
        customerName,
        customerEmail,
        customerPhone,
        orderNote,
        returnUrl,
      }),
    });
  } catch (networkError) {
    console.error('[Cashfree] Network error while creating payment session.', networkError);
    throw new Error('Network error while contacting payment server. Please check backend/CORS configuration.');
  }

  const text = await response.text().catch(() => '');

  if (!response.ok) {
    const message = parseApiError(response, text);
    console.error('[Cashfree] Backend responded with non-OK status for payment session.', {
      status: response.status,
      body: text,
    });
    throw new Error(message);
  }

  const data = text ? JSON.parse(text) : {};
  const paymentSessionId =
    data?.paymentSessionId || data?.payment_session_id || data?.payment_sessionId;

  if (!paymentSessionId) {
    console.error('[Cashfree] Backend did not return a valid payment session id.', data);
    throw new Error('Cashfree payment session could not be generated by the backend.');
  }

  console.log('[Cashfree] Received payment session from backend.', { paymentSessionId });

  return { ...data, paymentSessionId };
}

export async function verifyCashfreePayment(orderId) {
  if (!orderId) {
    throw new Error('Order ID is required to verify payment.');
  }

  console.log('[Cashfree] Verifying payment for order...', { orderId });

  const response = await fetch(`${CASHFREE_VERIFY_ENDPOINT}?order_id=${encodeURIComponent(orderId)}`);

  const text = await response.text().catch(() => '');

  if (!response.ok) {
    const message = parseApiError(response, text);
    throw new Error(message);
  }

  const data = text ? JSON.parse(text) : {};
  console.log('[Cashfree] Verification response.', data);

  return data;
}
